version: '3.8'

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data


networks:
  net: